import uuid
import streamlit as st

from interface import config


def initiate_session_state() -> None:
    if "session_id" not in st.session_state:
        st.session_state["session_id"] = uuid.uuid4().hex

    # if "app_name" not in st.session_state:
    #     st.session_state["app_name"] = "main"


def page_config(layout: str = "centered", sidebar: str = "auto") -> None:
    st.set_page_config(
        page_title=config.TITLE,
        page_icon=config.LOGO_FILEPATH,
        layout=layout,
        initial_sidebar_state=sidebar,
        menu_items={
            "Get help": None,
            "Report a bug": None,
            "About": None,
        },
    )

    hide_navigation_sidebar()

    with open(config.STYLE_FILEPATH) as css:
        st.markdown(f"<style>{css.read()}</style>", unsafe_allow_html=True)


def hide_navigation_sidebar() -> None:
    """
    Hides the navigation buttons automatically
    generated by Streamlit.
    """

    # HTML code to hide the navigation buttons automatically
    # generated by the Streamlit
    no_sidebar_style = """
        <style>
            div[data-testid="stSidebarNav"] {display: none;}
        </style>
    """
    st.markdown(no_sidebar_style, unsafe_allow_html=True)
