import importlib
import pkgutil
import uuid

from importlib import resources
from typing import Any

import streamlit as st

from interface.auth import get_authenticator
import interface.pages
from interface.settings import Settings


DEFAULT_PAGE_ORDER: int = 10_000
settings = Settings()


def main() -> None:
    page_config(layout="centered", sidebar="auto")
    initiate_session_state()
    pages = get_pages()
    app_names = [get_app_name(label, pages) for label in pages]
    app_name_map = {get_app_name(label, pages): label for label in pages}

    authenticator = get_authenticator()
    sidebar(pages, authenticator)

    app_name = st.session_state.get("app_name", "Página Principal")
    if app_name in app_names:
        module_key = app_name_map[app_name]
        if page_requires_auth(pages[module_key]) and not is_authenticated():
            st.warning("Faça login para acessar esta aplicação.")
            return
        pages[module_key].render()
    else:
        st.title(settings.app_name)
        st.text(f"App '{app_name}' não encontrado.")


def initiate_session_state() -> None:
    if "session_id" not in st.session_state:
        st.session_state["session_id"] = uuid.uuid4().hex

    # if "app_name" not in st.session_state:
    #     st.session_state["app_name"] = "main"


def page_config(layout: str = "centered", sidebar: str = "auto") -> None:
    logo_path = resources.files("interface") / settings.app_settings.logo_filepath
    st.set_page_config(
        page_title=settings.app_settings.name,
        page_icon=logo_path,
        layout=layout,
        initial_sidebar_state=sidebar,
        menu_items={
            "Get help": None,
            "Report a bug": None,
            "About": None,
        },
    )

    hide_navigation_sidebar()

    style_path = resources.files("interface") / settings.app_settings.style_filepath

    with open(style_path) as css:
        st.markdown(f"<style>{css.read()}</style>", unsafe_allow_html=True)


def hide_navigation_sidebar() -> None:
    """
    Hides the navigation buttons automatically
    generated by Streamlit.
    """

    # HTML code to hide the navigation buttons automatically
    # generated by the Streamlit
    no_sidebar_style = """
        <style>
            div[data-testid="stSidebarNav"] {display: none;}
        </style>
    """
    st.markdown(no_sidebar_style, unsafe_allow_html=True)


def sidebar(pages: dict[str, Any], authenticator):
    with st.sidebar:
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            logo_path = resources.files("interface") / "assets" / "logo.png"
            st.image(logo_path, width=150)

        render_login(authenticator)

    st.sidebar.header("Configurações")

    pages_list = get_ordered_page_names(pages)

    if pages_list:
        st.sidebar.selectbox(
            "Aplicação",
            pages_list,
            placeholder="Selecione o app",
            key="app_name",
            on_change=update_app_name,
        )


def update_app_name():
    pass


def render_login(authenticator) -> None:
    auth_status = st.session_state.get("authentication_status")
    if auth_status:
        authenticator.logout(location="sidebar")
        st.caption(f"Logado como: {st.session_state.get('name', '')}")
        return

    try:
        authenticator.login(location="sidebar")
    except Exception as exc:
        st.error(exc)

    auth_status = st.session_state.get("authentication_status")
    if auth_status is False:
        st.error("Usuário ou senha incorretos.")


def is_authenticated() -> bool:
    return bool(st.session_state.get("authentication_status"))


def page_requires_auth(module: Any) -> bool:
    return bool(getattr(module, "requires_auth", False))


def get_pages():
    """
    Lista todos os módulos em 'interface.pages' e retorna um dicionário
    com o nome do módulo e a referência do módulo.
    """
    pages = {}
    package = interface.pages

    for _, module_name, is_pkg in pkgutil.iter_modules(package.__path__):
        if not is_pkg:  # Ignorar pacotes, listar apenas módulos
            module_path = f"{package.__name__}.{module_name}"
            module = importlib.import_module(module_path)
            pages[module_name] = module

    return pages


def get_app_name(app_name: str, pages: dict[str, Any]):
    if module := pages.get(app_name):
        return module.name
    return app_name


def get_page_order(module: Any) -> int:
    order = getattr(module, "order", None)
    if isinstance(order, (int, float)):
        return int(order)
    return DEFAULT_PAGE_ORDER


def get_ordered_page_names(pages: dict[str, Any]) -> list[str]:
    page_items = []
    for app_name, module in pages.items():
        page_items.append((get_page_order(module), get_app_name(app_name, pages)))

    page_items.sort(key=lambda item: (item[0], item[1]))
    return [name for _, name in page_items]


if __name__ == "__main__":
    main()
