FROM python:3.11

WORKDIR /app

ENV PIP_DISABLE_PIP_VERSION_CHECK=on

# Instaling dependencies
COPY ./requirements.txt ./
COPY ./pyproject.toml ./
COPY ./README.md ./
COPY ./src ./src
COPY ./app.py ./
RUN pip install --no-cache-dir -r requirements.txt

# Installing aplication
COPY ./.streamlit ./.streamlit
COPY ./LICENSE.txt ./

EXPOSE 8501

RUN chmod -R a+x .

CMD ["streamlit", "run", "app.py"]
